// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/KeyValueResponse.proto

package ca.NetSysLab.ProtocolBuffers;

public final class KeyValueResponse {
  private KeyValueResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KVResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KVResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 errCode = 1;</code>
     * @return The errCode.
     */
    int getErrCode();

    /**
     * <code>optional bytes value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 2;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>optional int32 pid = 3;</code>
     * @return Whether the pid field is set.
     */
    boolean hasPid();
    /**
     * <code>optional int32 pid = 3;</code>
     * @return The pid.
     */
    int getPid();

    /**
     * <code>optional int32 version = 4;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 4;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return Whether the overloadWaitTime field is set.
     */
    boolean hasOverloadWaitTime();
    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return The overloadWaitTime.
     */
    int getOverloadWaitTime();

    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return Whether the membershipCount field is set.
     */
    boolean hasMembershipCount();
    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return The membershipCount.
     */
    int getMembershipCount();

    /**
     * <code>repeated int64 lastAliveTimestamps = 7;</code>
     * @return A list containing the lastAliveTimestamps.
     */
    java.util.List<java.lang.Long> getLastAliveTimestampsList();
    /**
     * <code>repeated int64 lastAliveTimestamps = 7;</code>
     * @return The count of lastAliveTimestamps.
     */
    int getLastAliveTimestampsCount();
    /**
     * <code>repeated int64 lastAliveTimestamps = 7;</code>
     * @param index The index of the element to return.
     * @return The lastAliveTimestamps at the given index.
     */
    long getLastAliveTimestamps(int index);

    /**
     * <code>optional int64 keyValueTimestamp = 8;</code>
     * @return Whether the keyValueTimestamp field is set.
     */
    boolean hasKeyValueTimestamp();
    /**
     * <code>optional int64 keyValueTimestamp = 8;</code>
     * @return The keyValueTimestamp.
     */
    long getKeyValueTimestamp();
  }
  /**
   * Protobuf type {@code KVResponse}
   */
  public static final class KVResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KVResponse)
      KVResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KVResponse.newBuilder() to construct.
    private KVResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KVResponse() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      lastAliveTimestamps_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KVResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.class, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_ = 0;
    /**
     * <code>uint32 errCode = 1;</code>
     * @return The errCode.
     */
    @java.lang.Override
    public int getErrCode() {
      return errCode_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int PID_FIELD_NUMBER = 3;
    private int pid_ = 0;
    /**
     * <code>optional int32 pid = 3;</code>
     * @return Whether the pid field is set.
     */
    @java.lang.Override
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 pid = 3;</code>
     * @return The pid.
     */
    @java.lang.Override
    public int getPid() {
      return pid_;
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_ = 0;
    /**
     * <code>optional int32 version = 4;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 version = 4;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int OVERLOADWAITTIME_FIELD_NUMBER = 5;
    private int overloadWaitTime_ = 0;
    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return Whether the overloadWaitTime field is set.
     */
    @java.lang.Override
    public boolean hasOverloadWaitTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 overloadWaitTime = 5;</code>
     * @return The overloadWaitTime.
     */
    @java.lang.Override
    public int getOverloadWaitTime() {
      return overloadWaitTime_;
    }

    public static final int MEMBERSHIPCOUNT_FIELD_NUMBER = 6;
    private int membershipCount_ = 0;
    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return Whether the membershipCount field is set.
     */
    @java.lang.Override
    public boolean hasMembershipCount() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 membershipCount = 6;</code>
     * @return The membershipCount.
     */
    @java.lang.Override
    public int getMembershipCount() {
      return membershipCount_;
    }

    public static final int LASTALIVETIMESTAMPS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList lastAliveTimestamps_;
    /**
     * <code>repeated int64 lastAliveTimestamps = 7;</code>
     * @return A list containing the lastAliveTimestamps.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getLastAliveTimestampsList() {
      return lastAliveTimestamps_;
    }
    /**
     * <code>repeated int64 lastAliveTimestamps = 7;</code>
     * @return The count of lastAliveTimestamps.
     */
    public int getLastAliveTimestampsCount() {
      return lastAliveTimestamps_.size();
    }
    /**
     * <code>repeated int64 lastAliveTimestamps = 7;</code>
     * @param index The index of the element to return.
     * @return The lastAliveTimestamps at the given index.
     */
    public long getLastAliveTimestamps(int index) {
      return lastAliveTimestamps_.getLong(index);
    }
    private int lastAliveTimestampsMemoizedSerializedSize = -1;

    public static final int KEYVALUETIMESTAMP_FIELD_NUMBER = 8;
    private long keyValueTimestamp_ = 0L;
    /**
     * <code>optional int64 keyValueTimestamp = 8;</code>
     * @return Whether the keyValueTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasKeyValueTimestamp() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 keyValueTimestamp = 8;</code>
     * @return The keyValueTimestamp.
     */
    @java.lang.Override
    public long getKeyValueTimestamp() {
      return keyValueTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (errCode_ != 0) {
        output.writeUInt32(1, errCode_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(2, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, pid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, version_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(5, overloadWaitTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(6, membershipCount_);
      }
      if (getLastAliveTimestampsList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(lastAliveTimestampsMemoizedSerializedSize);
      }
      for (int i = 0; i < lastAliveTimestamps_.size(); i++) {
        output.writeInt64NoTag(lastAliveTimestamps_.getLong(i));
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(8, keyValueTimestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errCode_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, version_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, overloadWaitTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, membershipCount_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lastAliveTimestamps_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(lastAliveTimestamps_.getLong(i));
        }
        size += dataSize;
        if (!getLastAliveTimestampsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        lastAliveTimestampsMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, keyValueTimestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse other = (ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse) obj;

      if (getErrCode()
          != other.getErrCode()) return false;
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (hasPid() != other.hasPid()) return false;
      if (hasPid()) {
        if (getPid()
            != other.getPid()) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasOverloadWaitTime() != other.hasOverloadWaitTime()) return false;
      if (hasOverloadWaitTime()) {
        if (getOverloadWaitTime()
            != other.getOverloadWaitTime()) return false;
      }
      if (hasMembershipCount() != other.hasMembershipCount()) return false;
      if (hasMembershipCount()) {
        if (getMembershipCount()
            != other.getMembershipCount()) return false;
      }
      if (!getLastAliveTimestampsList()
          .equals(other.getLastAliveTimestampsList())) return false;
      if (hasKeyValueTimestamp() != other.hasKeyValueTimestamp()) return false;
      if (hasKeyValueTimestamp()) {
        if (getKeyValueTimestamp()
            != other.getKeyValueTimestamp()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasPid()) {
        hash = (37 * hash) + PID_FIELD_NUMBER;
        hash = (53 * hash) + getPid();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasOverloadWaitTime()) {
        hash = (37 * hash) + OVERLOADWAITTIME_FIELD_NUMBER;
        hash = (53 * hash) + getOverloadWaitTime();
      }
      if (hasMembershipCount()) {
        hash = (37 * hash) + MEMBERSHIPCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getMembershipCount();
      }
      if (getLastAliveTimestampsCount() > 0) {
        hash = (37 * hash) + LASTALIVETIMESTAMPS_FIELD_NUMBER;
        hash = (53 * hash) + getLastAliveTimestampsList().hashCode();
      }
      if (hasKeyValueTimestamp()) {
        hash = (37 * hash) + KEYVALUETIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getKeyValueTimestamp());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KVResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KVResponse)
        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.class, ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        errCode_ = 0;
        value_ = com.google.protobuf.ByteString.EMPTY;
        pid_ = 0;
        version_ = 0;
        overloadWaitTime_ = 0;
        membershipCount_ = 0;
        lastAliveTimestamps_ = emptyLongList();
        keyValueTimestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.internal_static_KVResponse_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse build() {
        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse buildPartial() {
        ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result = new ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result) {
        if (((bitField0_ & 0x00000040) != 0)) {
          lastAliveTimestamps_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.lastAliveTimestamps_ = lastAliveTimestamps_;
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.errCode_ = errCode_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pid_ = pid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.overloadWaitTime_ = overloadWaitTime_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.membershipCount_ = membershipCount_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.keyValueTimestamp_ = keyValueTimestamp_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse other) {
        if (other == ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse.getDefaultInstance()) return this;
        if (other.getErrCode() != 0) {
          setErrCode(other.getErrCode());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasOverloadWaitTime()) {
          setOverloadWaitTime(other.getOverloadWaitTime());
        }
        if (other.hasMembershipCount()) {
          setMembershipCount(other.getMembershipCount());
        }
        if (!other.lastAliveTimestamps_.isEmpty()) {
          if (lastAliveTimestamps_.isEmpty()) {
            lastAliveTimestamps_ = other.lastAliveTimestamps_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureLastAliveTimestampsIsMutable();
            lastAliveTimestamps_.addAll(other.lastAliveTimestamps_);
          }
          onChanged();
        }
        if (other.hasKeyValueTimestamp()) {
          setKeyValueTimestamp(other.getKeyValueTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                errCode_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                pid_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                overloadWaitTime_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                membershipCount_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                long v = input.readInt64();
                ensureLastAliveTimestampsIsMutable();
                lastAliveTimestamps_.addLong(v);
                break;
              } // case 56
              case 58: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureLastAliveTimestampsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  lastAliveTimestamps_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 58
              case 64: {
                keyValueTimestamp_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int errCode_ ;
      /**
       * <code>uint32 errCode = 1;</code>
       * @return The errCode.
       */
      @java.lang.Override
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>uint32 errCode = 1;</code>
       * @param value The errCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrCode(int value) {
        
        errCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 errCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 2;</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>optional int32 pid = 3;</code>
       * @return Whether the pid field is set.
       */
      @java.lang.Override
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 pid = 3;</code>
       * @return The pid.
       */
      @java.lang.Override
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 3;</code>
       * @param value The pid to set.
       * @return This builder for chaining.
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>optional int32 version = 4;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0;
        onChanged();
        return this;
      }

      private int overloadWaitTime_ ;
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @return Whether the overloadWaitTime field is set.
       */
      @java.lang.Override
      public boolean hasOverloadWaitTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @return The overloadWaitTime.
       */
      @java.lang.Override
      public int getOverloadWaitTime() {
        return overloadWaitTime_;
      }
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @param value The overloadWaitTime to set.
       * @return This builder for chaining.
       */
      public Builder setOverloadWaitTime(int value) {
        
        overloadWaitTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 overloadWaitTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOverloadWaitTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        overloadWaitTime_ = 0;
        onChanged();
        return this;
      }

      private int membershipCount_ ;
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @return Whether the membershipCount field is set.
       */
      @java.lang.Override
      public boolean hasMembershipCount() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @return The membershipCount.
       */
      @java.lang.Override
      public int getMembershipCount() {
        return membershipCount_;
      }
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @param value The membershipCount to set.
       * @return This builder for chaining.
       */
      public Builder setMembershipCount(int value) {
        
        membershipCount_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 membershipCount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMembershipCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        membershipCount_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList lastAliveTimestamps_ = emptyLongList();
      private void ensureLastAliveTimestampsIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          lastAliveTimestamps_ = mutableCopy(lastAliveTimestamps_);
          bitField0_ |= 0x00000040;
        }
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 7;</code>
       * @return A list containing the lastAliveTimestamps.
       */
      public java.util.List<java.lang.Long>
          getLastAliveTimestampsList() {
        return ((bitField0_ & 0x00000040) != 0) ?
                 java.util.Collections.unmodifiableList(lastAliveTimestamps_) : lastAliveTimestamps_;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 7;</code>
       * @return The count of lastAliveTimestamps.
       */
      public int getLastAliveTimestampsCount() {
        return lastAliveTimestamps_.size();
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 7;</code>
       * @param index The index of the element to return.
       * @return The lastAliveTimestamps at the given index.
       */
      public long getLastAliveTimestamps(int index) {
        return lastAliveTimestamps_.getLong(index);
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 7;</code>
       * @param index The index to set the value at.
       * @param value The lastAliveTimestamps to set.
       * @return This builder for chaining.
       */
      public Builder setLastAliveTimestamps(
          int index, long value) {
        
        ensureLastAliveTimestampsIsMutable();
        lastAliveTimestamps_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 7;</code>
       * @param value The lastAliveTimestamps to add.
       * @return This builder for chaining.
       */
      public Builder addLastAliveTimestamps(long value) {
        
        ensureLastAliveTimestampsIsMutable();
        lastAliveTimestamps_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 7;</code>
       * @param values The lastAliveTimestamps to add.
       * @return This builder for chaining.
       */
      public Builder addAllLastAliveTimestamps(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureLastAliveTimestampsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lastAliveTimestamps_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastAliveTimestamps() {
        lastAliveTimestamps_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private long keyValueTimestamp_ ;
      /**
       * <code>optional int64 keyValueTimestamp = 8;</code>
       * @return Whether the keyValueTimestamp field is set.
       */
      @java.lang.Override
      public boolean hasKeyValueTimestamp() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional int64 keyValueTimestamp = 8;</code>
       * @return The keyValueTimestamp.
       */
      @java.lang.Override
      public long getKeyValueTimestamp() {
        return keyValueTimestamp_;
      }
      /**
       * <code>optional int64 keyValueTimestamp = 8;</code>
       * @param value The keyValueTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setKeyValueTimestamp(long value) {
        
        keyValueTimestamp_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 keyValueTimestamp = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyValueTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        keyValueTimestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KVResponse)
    }

    // @@protoc_insertion_point(class_scope:KVResponse)
    private static final ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse();
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KVResponse>
        PARSER = new com.google.protobuf.AbstractParser<KVResponse>() {
      @java.lang.Override
      public KVResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KVResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KVResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KVResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KVResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034proto/KeyValueResponse.proto\"\260\002\n\nKVRes" +
      "ponse\022\017\n\007errCode\030\001 \001(\r\022\022\n\005value\030\002 \001(\014H\000\210" +
      "\001\001\022\020\n\003pid\030\003 \001(\005H\001\210\001\001\022\024\n\007version\030\004 \001(\005H\002\210" +
      "\001\001\022\035\n\020overloadWaitTime\030\005 \001(\005H\003\210\001\001\022\034\n\017mem" +
      "bershipCount\030\006 \001(\005H\004\210\001\001\022\033\n\023lastAliveTime" +
      "stamps\030\007 \003(\003\022\036\n\021keyValueTimestamp\030\010 \001(\003H" +
      "\005\210\001\001B\010\n\006_valueB\006\n\004_pidB\n\n\010_versionB\023\n\021_o" +
      "verloadWaitTimeB\022\n\020_membershipCountB\024\n\022_" +
      "keyValueTimestampB0\n\034ca.NetSysLab.Protoc" +
      "olBuffersB\020KeyValueResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_KVResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KVResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KVResponse_descriptor,
        new java.lang.String[] { "ErrCode", "Value", "Pid", "Version", "OverloadWaitTime", "MembershipCount", "LastAliveTimestamps", "KeyValueTimestamp", "Value", "Pid", "Version", "OverloadWaitTime", "MembershipCount", "KeyValueTimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
