// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/KeyValueRequest.proto

package ca.NetSysLab.ProtocolBuffers;

public final class KeyValueRequest {
  private KeyValueRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PutOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Put)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes key = 1;</code>
     * @return The key.
     */
    com.google.protobuf.ByteString getKey();

    /**
     * <code>bytes value = 2;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>int32 version = 3;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Put}
   */
  public static final class Put extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Put)
      PutOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Put.newBuilder() to construct.
    private Put(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Put() {
      key_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Put();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_Put_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_Put_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.class, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_ = 0;
    /**
     * <code>int32 version = 3;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!key_.isEmpty()) {
        output.writeBytes(1, key_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(2, value_);
      }
      if (version_ != 0) {
        output.writeInt32(3, version_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!key_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, key_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put other = (ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Put}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Put)
        ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_Put_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_Put_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.class, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = com.google.protobuf.ByteString.EMPTY;
        value_ = com.google.protobuf.ByteString.EMPTY;
        version_ = 0;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_Put_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put build() {
        ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put buildPartial() {
        ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put result = new ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put other) {
        if (other == ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.getDefaultInstance()) return this;
        if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
          setKey(other.getKey());
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>bytes key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 3;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 3;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Put)
    }

    // @@protoc_insertion_point(class_scope:Put)
    private static final ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put();
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Put>
        PARSER = new com.google.protobuf.AbstractParser<Put>() {
      @java.lang.Override
      public Put parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Put> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Put> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KVRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KVRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 command = 1;</code>
     * @return The command.
     */
    int getCommand();

    /**
     * <code>optional bytes key = 2;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>optional bytes key = 2;</code>
     * @return The key.
     */
    com.google.protobuf.ByteString getKey();

    /**
     * <code>optional bytes value = 3;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 3;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>optional int32 version = 4;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 4;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>optional string clientAddress = 5;</code>
     * @return Whether the clientAddress field is set.
     */
    boolean hasClientAddress();
    /**
     * <code>optional string clientAddress = 5;</code>
     * @return The clientAddress.
     */
    java.lang.String getClientAddress();
    /**
     * <code>optional string clientAddress = 5;</code>
     * @return The bytes for clientAddress.
     */
    com.google.protobuf.ByteString
        getClientAddressBytes();

    /**
     * <code>optional int32 clientPort = 6;</code>
     * @return Whether the clientPort field is set.
     */
    boolean hasClientPort();
    /**
     * <code>optional int32 clientPort = 6;</code>
     * @return The clientPort.
     */
    int getClientPort();

    /**
     * <code>optional int64 keyValueTimestamp = 7;</code>
     * @return Whether the keyValueTimestamp field is set.
     */
    boolean hasKeyValueTimestamp();
    /**
     * <code>optional int64 keyValueTimestamp = 7;</code>
     * @return The keyValueTimestamp.
     */
    long getKeyValueTimestamp();

    /**
     * <code>repeated int64 lastAliveTimestamps = 8;</code>
     * @return A list containing the lastAliveTimestamps.
     */
    java.util.List<java.lang.Long> getLastAliveTimestampsList();
    /**
     * <code>repeated int64 lastAliveTimestamps = 8;</code>
     * @return The count of lastAliveTimestamps.
     */
    int getLastAliveTimestampsCount();
    /**
     * <code>repeated int64 lastAliveTimestamps = 8;</code>
     * @param index The index of the element to return.
     * @return The lastAliveTimestamps at the given index.
     */
    long getLastAliveTimestamps(int index);

    /**
     * <code>optional int32 chainCount = 9;</code>
     * @return Whether the chainCount field is set.
     */
    boolean hasChainCount();
    /**
     * <code>optional int32 chainCount = 9;</code>
     * @return The chainCount.
     */
    int getChainCount();

    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put> 
        getBatchPutList();
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put getBatchPut(int index);
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    int getBatchPutCount();
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    java.util.List<? extends ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder> 
        getBatchPutOrBuilderList();
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder getBatchPutOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code KVRequest}
   */
  public static final class KVRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KVRequest)
      KVRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KVRequest.newBuilder() to construct.
    private KVRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KVRequest() {
      key_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
      clientAddress_ = "";
      lastAliveTimestamps_ = emptyLongList();
      batchPut_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KVRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_KVRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_KVRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.class, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.Builder.class);
    }

    private int bitField0_;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_ = 0;
    /**
     * <code>uint32 command = 1;</code>
     * @return The command.
     */
    @java.lang.Override
    public int getCommand() {
      return command_;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes key = 2;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes value = 3;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_ = 0;
    /**
     * <code>optional int32 version = 4;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 version = 4;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int CLIENTADDRESS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object clientAddress_ = "";
    /**
     * <code>optional string clientAddress = 5;</code>
     * @return Whether the clientAddress field is set.
     */
    @java.lang.Override
    public boolean hasClientAddress() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string clientAddress = 5;</code>
     * @return The clientAddress.
     */
    @java.lang.Override
    public java.lang.String getClientAddress() {
      java.lang.Object ref = clientAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientAddress_ = s;
        return s;
      }
    }
    /**
     * <code>optional string clientAddress = 5;</code>
     * @return The bytes for clientAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientAddressBytes() {
      java.lang.Object ref = clientAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTPORT_FIELD_NUMBER = 6;
    private int clientPort_ = 0;
    /**
     * <code>optional int32 clientPort = 6;</code>
     * @return Whether the clientPort field is set.
     */
    @java.lang.Override
    public boolean hasClientPort() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 clientPort = 6;</code>
     * @return The clientPort.
     */
    @java.lang.Override
    public int getClientPort() {
      return clientPort_;
    }

    public static final int KEYVALUETIMESTAMP_FIELD_NUMBER = 7;
    private long keyValueTimestamp_ = 0L;
    /**
     * <code>optional int64 keyValueTimestamp = 7;</code>
     * @return Whether the keyValueTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasKeyValueTimestamp() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 keyValueTimestamp = 7;</code>
     * @return The keyValueTimestamp.
     */
    @java.lang.Override
    public long getKeyValueTimestamp() {
      return keyValueTimestamp_;
    }

    public static final int LASTALIVETIMESTAMPS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList lastAliveTimestamps_;
    /**
     * <code>repeated int64 lastAliveTimestamps = 8;</code>
     * @return A list containing the lastAliveTimestamps.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getLastAliveTimestampsList() {
      return lastAliveTimestamps_;
    }
    /**
     * <code>repeated int64 lastAliveTimestamps = 8;</code>
     * @return The count of lastAliveTimestamps.
     */
    public int getLastAliveTimestampsCount() {
      return lastAliveTimestamps_.size();
    }
    /**
     * <code>repeated int64 lastAliveTimestamps = 8;</code>
     * @param index The index of the element to return.
     * @return The lastAliveTimestamps at the given index.
     */
    public long getLastAliveTimestamps(int index) {
      return lastAliveTimestamps_.getLong(index);
    }
    private int lastAliveTimestampsMemoizedSerializedSize = -1;

    public static final int CHAINCOUNT_FIELD_NUMBER = 9;
    private int chainCount_ = 0;
    /**
     * <code>optional int32 chainCount = 9;</code>
     * @return Whether the chainCount field is set.
     */
    @java.lang.Override
    public boolean hasChainCount() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 chainCount = 9;</code>
     * @return The chainCount.
     */
    @java.lang.Override
    public int getChainCount() {
      return chainCount_;
    }

    public static final int BATCHPUT_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put> batchPut_;
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    @java.lang.Override
    public java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put> getBatchPutList() {
      return batchPut_;
    }
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder> 
        getBatchPutOrBuilderList() {
      return batchPut_;
    }
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    @java.lang.Override
    public int getBatchPutCount() {
      return batchPut_.size();
    }
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put getBatchPut(int index) {
      return batchPut_.get(index);
    }
    /**
     * <code>repeated .Put batchPut = 10;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder getBatchPutOrBuilder(
        int index) {
      return batchPut_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (command_ != 0) {
        output.writeUInt32(1, command_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(2, key_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(3, value_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, version_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientAddress_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(6, clientPort_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(7, keyValueTimestamp_);
      }
      if (getLastAliveTimestampsList().size() > 0) {
        output.writeUInt32NoTag(66);
        output.writeUInt32NoTag(lastAliveTimestampsMemoizedSerializedSize);
      }
      for (int i = 0; i < lastAliveTimestamps_.size(); i++) {
        output.writeInt64NoTag(lastAliveTimestamps_.getLong(i));
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(9, chainCount_);
      }
      for (int i = 0; i < batchPut_.size(); i++) {
        output.writeMessage(10, batchPut_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (command_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, command_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, key_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, version_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientAddress_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, clientPort_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, keyValueTimestamp_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < lastAliveTimestamps_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(lastAliveTimestamps_.getLong(i));
        }
        size += dataSize;
        if (!getLastAliveTimestampsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        lastAliveTimestampsMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, chainCount_);
      }
      for (int i = 0; i < batchPut_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, batchPut_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest other = (ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest) obj;

      if (getCommand()
          != other.getCommand()) return false;
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasClientAddress() != other.hasClientAddress()) return false;
      if (hasClientAddress()) {
        if (!getClientAddress()
            .equals(other.getClientAddress())) return false;
      }
      if (hasClientPort() != other.hasClientPort()) return false;
      if (hasClientPort()) {
        if (getClientPort()
            != other.getClientPort()) return false;
      }
      if (hasKeyValueTimestamp() != other.hasKeyValueTimestamp()) return false;
      if (hasKeyValueTimestamp()) {
        if (getKeyValueTimestamp()
            != other.getKeyValueTimestamp()) return false;
      }
      if (!getLastAliveTimestampsList()
          .equals(other.getLastAliveTimestampsList())) return false;
      if (hasChainCount() != other.hasChainCount()) return false;
      if (hasChainCount()) {
        if (getChainCount()
            != other.getChainCount()) return false;
      }
      if (!getBatchPutList()
          .equals(other.getBatchPutList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasClientAddress()) {
        hash = (37 * hash) + CLIENTADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getClientAddress().hashCode();
      }
      if (hasClientPort()) {
        hash = (37 * hash) + CLIENTPORT_FIELD_NUMBER;
        hash = (53 * hash) + getClientPort();
      }
      if (hasKeyValueTimestamp()) {
        hash = (37 * hash) + KEYVALUETIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getKeyValueTimestamp());
      }
      if (getLastAliveTimestampsCount() > 0) {
        hash = (37 * hash) + LASTALIVETIMESTAMPS_FIELD_NUMBER;
        hash = (53 * hash) + getLastAliveTimestampsList().hashCode();
      }
      if (hasChainCount()) {
        hash = (37 * hash) + CHAINCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getChainCount();
      }
      if (getBatchPutCount() > 0) {
        hash = (37 * hash) + BATCHPUT_FIELD_NUMBER;
        hash = (53 * hash) + getBatchPutList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KVRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KVRequest)
        ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_KVRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_KVRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.class, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        command_ = 0;
        key_ = com.google.protobuf.ByteString.EMPTY;
        value_ = com.google.protobuf.ByteString.EMPTY;
        version_ = 0;
        clientAddress_ = "";
        clientPort_ = 0;
        keyValueTimestamp_ = 0L;
        lastAliveTimestamps_ = emptyLongList();
        chainCount_ = 0;
        if (batchPutBuilder_ == null) {
          batchPut_ = java.util.Collections.emptyList();
        } else {
          batchPut_ = null;
          batchPutBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.internal_static_KVRequest_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest build() {
        ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest buildPartial() {
        ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest result = new ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest result) {
        if (((bitField0_ & 0x00000080) != 0)) {
          lastAliveTimestamps_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.lastAliveTimestamps_ = lastAliveTimestamps_;
        if (batchPutBuilder_ == null) {
          if (((bitField0_ & 0x00000200) != 0)) {
            batchPut_ = java.util.Collections.unmodifiableList(batchPut_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.batchPut_ = batchPut_;
        } else {
          result.batchPut_ = batchPutBuilder_.build();
        }
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.command_ = command_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.key_ = key_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.clientAddress_ = clientAddress_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.clientPort_ = clientPort_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.keyValueTimestamp_ = keyValueTimestamp_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.chainCount_ = chainCount_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest other) {
        if (other == ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.getDefaultInstance()) return this;
        if (other.getCommand() != 0) {
          setCommand(other.getCommand());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasClientAddress()) {
          clientAddress_ = other.clientAddress_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasClientPort()) {
          setClientPort(other.getClientPort());
        }
        if (other.hasKeyValueTimestamp()) {
          setKeyValueTimestamp(other.getKeyValueTimestamp());
        }
        if (!other.lastAliveTimestamps_.isEmpty()) {
          if (lastAliveTimestamps_.isEmpty()) {
            lastAliveTimestamps_ = other.lastAliveTimestamps_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureLastAliveTimestampsIsMutable();
            lastAliveTimestamps_.addAll(other.lastAliveTimestamps_);
          }
          onChanged();
        }
        if (other.hasChainCount()) {
          setChainCount(other.getChainCount());
        }
        if (batchPutBuilder_ == null) {
          if (!other.batchPut_.isEmpty()) {
            if (batchPut_.isEmpty()) {
              batchPut_ = other.batchPut_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureBatchPutIsMutable();
              batchPut_.addAll(other.batchPut_);
            }
            onChanged();
          }
        } else {
          if (!other.batchPut_.isEmpty()) {
            if (batchPutBuilder_.isEmpty()) {
              batchPutBuilder_.dispose();
              batchPutBuilder_ = null;
              batchPut_ = other.batchPut_;
              bitField0_ = (bitField0_ & ~0x00000200);
              batchPutBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBatchPutFieldBuilder() : null;
            } else {
              batchPutBuilder_.addAllMessages(other.batchPut_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                command_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                clientAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                clientPort_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                keyValueTimestamp_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                long v = input.readInt64();
                ensureLastAliveTimestampsIsMutable();
                lastAliveTimestamps_.addLong(v);
                break;
              } // case 64
              case 66: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureLastAliveTimestampsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  lastAliveTimestamps_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 66
              case 72: {
                chainCount_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 82: {
                ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put m =
                    input.readMessage(
                        ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.parser(),
                        extensionRegistry);
                if (batchPutBuilder_ == null) {
                  ensureBatchPutIsMutable();
                  batchPut_.add(m);
                } else {
                  batchPutBuilder_.addMessage(m);
                }
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int command_ ;
      /**
       * <code>uint32 command = 1;</code>
       * @return The command.
       */
      @java.lang.Override
      public int getCommand() {
        return command_;
      }
      /**
       * <code>uint32 command = 1;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(int value) {
        
        command_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 command = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes key = 2;</code>
       * @return Whether the key field is set.
       */
      @java.lang.Override
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes key = 2;</code>
       * @return The key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>optional bytes key = 2;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 3;</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes value = 3;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 3;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>optional int32 version = 4;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientAddress_ = "";
      /**
       * <code>optional string clientAddress = 5;</code>
       * @return Whether the clientAddress field is set.
       */
      public boolean hasClientAddress() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string clientAddress = 5;</code>
       * @return The clientAddress.
       */
      public java.lang.String getClientAddress() {
        java.lang.Object ref = clientAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientAddress = 5;</code>
       * @return The bytes for clientAddress.
       */
      public com.google.protobuf.ByteString
          getClientAddressBytes() {
        java.lang.Object ref = clientAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientAddress = 5;</code>
       * @param value The clientAddress to set.
       * @return This builder for chaining.
       */
      public Builder setClientAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        clientAddress_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientAddress = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientAddress() {
        clientAddress_ = getDefaultInstance().getClientAddress();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientAddress = 5;</code>
       * @param value The bytes for clientAddress to set.
       * @return This builder for chaining.
       */
      public Builder setClientAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        clientAddress_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int clientPort_ ;
      /**
       * <code>optional int32 clientPort = 6;</code>
       * @return Whether the clientPort field is set.
       */
      @java.lang.Override
      public boolean hasClientPort() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 clientPort = 6;</code>
       * @return The clientPort.
       */
      @java.lang.Override
      public int getClientPort() {
        return clientPort_;
      }
      /**
       * <code>optional int32 clientPort = 6;</code>
       * @param value The clientPort to set.
       * @return This builder for chaining.
       */
      public Builder setClientPort(int value) {
        
        clientPort_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientPort = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientPort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        clientPort_ = 0;
        onChanged();
        return this;
      }

      private long keyValueTimestamp_ ;
      /**
       * <code>optional int64 keyValueTimestamp = 7;</code>
       * @return Whether the keyValueTimestamp field is set.
       */
      @java.lang.Override
      public boolean hasKeyValueTimestamp() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int64 keyValueTimestamp = 7;</code>
       * @return The keyValueTimestamp.
       */
      @java.lang.Override
      public long getKeyValueTimestamp() {
        return keyValueTimestamp_;
      }
      /**
       * <code>optional int64 keyValueTimestamp = 7;</code>
       * @param value The keyValueTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setKeyValueTimestamp(long value) {
        
        keyValueTimestamp_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 keyValueTimestamp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyValueTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        keyValueTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList lastAliveTimestamps_ = emptyLongList();
      private void ensureLastAliveTimestampsIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          lastAliveTimestamps_ = mutableCopy(lastAliveTimestamps_);
          bitField0_ |= 0x00000080;
        }
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 8;</code>
       * @return A list containing the lastAliveTimestamps.
       */
      public java.util.List<java.lang.Long>
          getLastAliveTimestampsList() {
        return ((bitField0_ & 0x00000080) != 0) ?
                 java.util.Collections.unmodifiableList(lastAliveTimestamps_) : lastAliveTimestamps_;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 8;</code>
       * @return The count of lastAliveTimestamps.
       */
      public int getLastAliveTimestampsCount() {
        return lastAliveTimestamps_.size();
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 8;</code>
       * @param index The index of the element to return.
       * @return The lastAliveTimestamps at the given index.
       */
      public long getLastAliveTimestamps(int index) {
        return lastAliveTimestamps_.getLong(index);
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 8;</code>
       * @param index The index to set the value at.
       * @param value The lastAliveTimestamps to set.
       * @return This builder for chaining.
       */
      public Builder setLastAliveTimestamps(
          int index, long value) {
        
        ensureLastAliveTimestampsIsMutable();
        lastAliveTimestamps_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 8;</code>
       * @param value The lastAliveTimestamps to add.
       * @return This builder for chaining.
       */
      public Builder addLastAliveTimestamps(long value) {
        
        ensureLastAliveTimestampsIsMutable();
        lastAliveTimestamps_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 8;</code>
       * @param values The lastAliveTimestamps to add.
       * @return This builder for chaining.
       */
      public Builder addAllLastAliveTimestamps(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureLastAliveTimestampsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lastAliveTimestamps_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lastAliveTimestamps = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastAliveTimestamps() {
        lastAliveTimestamps_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      private int chainCount_ ;
      /**
       * <code>optional int32 chainCount = 9;</code>
       * @return Whether the chainCount field is set.
       */
      @java.lang.Override
      public boolean hasChainCount() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional int32 chainCount = 9;</code>
       * @return The chainCount.
       */
      @java.lang.Override
      public int getChainCount() {
        return chainCount_;
      }
      /**
       * <code>optional int32 chainCount = 9;</code>
       * @param value The chainCount to set.
       * @return This builder for chaining.
       */
      public Builder setChainCount(int value) {
        
        chainCount_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 chainCount = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainCount() {
        bitField0_ = (bitField0_ & ~0x00000100);
        chainCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put> batchPut_ =
        java.util.Collections.emptyList();
      private void ensureBatchPutIsMutable() {
        if (!((bitField0_ & 0x00000200) != 0)) {
          batchPut_ = new java.util.ArrayList<ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put>(batchPut_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder> batchPutBuilder_;

      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put> getBatchPutList() {
        if (batchPutBuilder_ == null) {
          return java.util.Collections.unmodifiableList(batchPut_);
        } else {
          return batchPutBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public int getBatchPutCount() {
        if (batchPutBuilder_ == null) {
          return batchPut_.size();
        } else {
          return batchPutBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put getBatchPut(int index) {
        if (batchPutBuilder_ == null) {
          return batchPut_.get(index);
        } else {
          return batchPutBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder setBatchPut(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put value) {
        if (batchPutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchPutIsMutable();
          batchPut_.set(index, value);
          onChanged();
        } else {
          batchPutBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder setBatchPut(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder builderForValue) {
        if (batchPutBuilder_ == null) {
          ensureBatchPutIsMutable();
          batchPut_.set(index, builderForValue.build());
          onChanged();
        } else {
          batchPutBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder addBatchPut(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put value) {
        if (batchPutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchPutIsMutable();
          batchPut_.add(value);
          onChanged();
        } else {
          batchPutBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder addBatchPut(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put value) {
        if (batchPutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchPutIsMutable();
          batchPut_.add(index, value);
          onChanged();
        } else {
          batchPutBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder addBatchPut(
          ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder builderForValue) {
        if (batchPutBuilder_ == null) {
          ensureBatchPutIsMutable();
          batchPut_.add(builderForValue.build());
          onChanged();
        } else {
          batchPutBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder addBatchPut(
          int index, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder builderForValue) {
        if (batchPutBuilder_ == null) {
          ensureBatchPutIsMutable();
          batchPut_.add(index, builderForValue.build());
          onChanged();
        } else {
          batchPutBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder addAllBatchPut(
          java.lang.Iterable<? extends ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put> values) {
        if (batchPutBuilder_ == null) {
          ensureBatchPutIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, batchPut_);
          onChanged();
        } else {
          batchPutBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder clearBatchPut() {
        if (batchPutBuilder_ == null) {
          batchPut_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          batchPutBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public Builder removeBatchPut(int index) {
        if (batchPutBuilder_ == null) {
          ensureBatchPutIsMutable();
          batchPut_.remove(index);
          onChanged();
        } else {
          batchPutBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder getBatchPutBuilder(
          int index) {
        return getBatchPutFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder getBatchPutOrBuilder(
          int index) {
        if (batchPutBuilder_ == null) {
          return batchPut_.get(index);  } else {
          return batchPutBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public java.util.List<? extends ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder> 
           getBatchPutOrBuilderList() {
        if (batchPutBuilder_ != null) {
          return batchPutBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(batchPut_);
        }
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder addBatchPutBuilder() {
        return getBatchPutFieldBuilder().addBuilder(
            ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.getDefaultInstance());
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder addBatchPutBuilder(
          int index) {
        return getBatchPutFieldBuilder().addBuilder(
            index, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.getDefaultInstance());
      }
      /**
       * <code>repeated .Put batchPut = 10;</code>
       */
      public java.util.List<ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder> 
           getBatchPutBuilderList() {
        return getBatchPutFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder> 
          getBatchPutFieldBuilder() {
        if (batchPutBuilder_ == null) {
          batchPutBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.Put.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.PutOrBuilder>(
                  batchPut_,
                  ((bitField0_ & 0x00000200) != 0),
                  getParentForChildren(),
                  isClean());
          batchPut_ = null;
        }
        return batchPutBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KVRequest)
    }

    // @@protoc_insertion_point(class_scope:KVRequest)
    private static final ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest();
    }

    public static ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KVRequest>
        PARSER = new com.google.protobuf.AbstractParser<KVRequest>() {
      @java.lang.Override
      public KVRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KVRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KVRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Put_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Put_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KVRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KVRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/KeyValueRequest.proto\"E\n\003Put\022\013\n\003" +
      "key\030\001 \001(\014\022\r\n\005value\030\002 \001(\014\022\017\n\007version\030\003 \001(" +
      "\005\022\021\n\ttimestamp\030\004 \001(\003\"\337\002\n\tKVRequest\022\017\n\007co" +
      "mmand\030\001 \001(\r\022\020\n\003key\030\002 \001(\014H\000\210\001\001\022\022\n\005value\030\003" +
      " \001(\014H\001\210\001\001\022\024\n\007version\030\004 \001(\005H\002\210\001\001\022\032\n\rclien" +
      "tAddress\030\005 \001(\tH\003\210\001\001\022\027\n\nclientPort\030\006 \001(\005H" +
      "\004\210\001\001\022\036\n\021keyValueTimestamp\030\007 \001(\003H\005\210\001\001\022\033\n\023" +
      "lastAliveTimestamps\030\010 \003(\003\022\027\n\nchainCount\030" +
      "\t \001(\005H\006\210\001\001\022\026\n\010batchPut\030\n \003(\0132\004.PutB\006\n\004_k" +
      "eyB\010\n\006_valueB\n\n\010_versionB\020\n\016_clientAddre" +
      "ssB\r\n\013_clientPortB\024\n\022_keyValueTimestampB" +
      "\r\n\013_chainCountB/\n\034ca.NetSysLab.ProtocolB" +
      "uffersB\017KeyValueRequestb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Put_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Put_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Put_descriptor,
        new java.lang.String[] { "Key", "Value", "Version", "Timestamp", });
    internal_static_KVRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_KVRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KVRequest_descriptor,
        new java.lang.String[] { "Command", "Key", "Value", "Version", "ClientAddress", "ClientPort", "KeyValueTimestamp", "LastAliveTimestamps", "ChainCount", "BatchPut", "Key", "Value", "Version", "ClientAddress", "ClientPort", "KeyValueTimestamp", "ChainCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
